# === ОСНОВНЫЕ ПАРАМЕТРЫ ===
seed: 42
output_dir: "models"
device: "auto"  # auto/cuda/cpu

# === МОДЕЛИ ===
vision_model: "efficientnet_b3"
text_model: "bert-base-uncased"

# === АРХИТЕКТУРА ===
hidden_dim: 768
dropout_rate: 0.3
image_size: 224

# === ОБУЧЕНИЕ ===
epochs: 30
batch_size: 12
num_workers: 0           # 0 для Windows, 4 для Linux

# Learning rates для разных компонентов
vision_lr: 0.00002
text_lr: 0.00002
fusion_lr: 0.0005

# === ОПТИМИЗАЦИЯ ===
weight_decay: 0.01
grad_clip: 1.0

# Планировщик Learning Rate (WARMUP + COSINE)
scheduler: "cosine"
warmup_epochs: 5
min_lr: 0.00000001

# === РАННЯЯ ОСТАНОВКА ===
early_stopping_patience: 20

# === ДОПОЛНИТЕЛЬНЫЕ ПАРАМЕТРЫ ОБУЧЕНИЯ ===
text_max_length: 128
accumulate_steps: 2
freeze_vision_epochs: 5
freeze_text_epochs: 0

# === АУГМЕНТАЦИИ ===
augmentation:
  # Настройка разрешения изображений
  image_size: 224
  # Умеренные геометрические трансформации
  affine_prob: 0.3
  affine_scale: [0.95, 1.05]
  affine_translate: [-0.03, 0.03]
  
  # Базовые аугментации
  horizontal_flip_prob: 0.5
  
  # Умеренные цветовые изменения
  color_jitter_brightness: 0.2
  color_jitter_contrast: 0.2
  color_jitter_saturation: 0.2
  color_jitter_hue: 0.05
  color_jitter_prob: 0.6
  
  # Геометрия
  rotation_range: [-5, 5]
  
  # Минимальное маскирование
  coarse_dropout_prob: 0.1
  coarse_dropout_holes_range: [1, 2]
  
  # Эластичность
  elastic_transform_prob: 0.0
  
  # Воспроизводимость
  transform_seed: 42

# === ПУТИ К ДАННЫМ ===
data_paths:
  dish_csv: "data/dish.csv"
  ingredients_csv: "data/ingredients.csv"
  images_dir: "data/images"

# === МЕТРИКИ ЦЕЛЕВЫЕ ===
target_mae: 50  # MAE должен быть меньше 50 ккал

# === ЛОГИРОВАНИЕ ===
logging:
  log_every_n_steps: 20
  save_checkpoints: true
  checkpoint_interval: 5

